apiVersion: v1
kind: Pod
metadata:
  generateName: macvlan-bridge-pod-dualstack
  labels:
    name: macvlan-bridge-pod-dualstack
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-bridge-dualstack
spec:
  containers:
  - name: macvlan-bridge-pod-dualstack
    image: bmeng/centos-network
    imagePullPolicy: IfNotPresent
