apiVersion: v1
kind: Pod
metadata:
  generateName: macvlan-private-pod-dualstack
  labels:
    name: macvlan-private-pod-dualstack
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-private-dualstack
spec:
  containers:
  - name: macvlan-private-pod-dualstack
    image: docker.io/aosqe/centos-network@sha256:48da37205f9b43424e0983d4c5e7e07f77b7ba1504bbe35e2f264c75dcb4cd15
    imagePullPolicy: IfNotPresent
