apiVersion: v1
kind: Pod
metadata:
  generateName: macvlan-bridge-pod-dualstack
  labels:
    name: macvlan-bridge-pod-dualstack
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-bridge-dualstack
spec:
  containers:
  - name: macvlan-bridge-pod-dualstack
    image: registry.ocp-edge-cluster.qe.lab.redhat.com:5000/openshift/centos-network
    imagePullPolicy: IfNotPresent
