apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-openshift
    name: hello-openshift
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: openshift/hello-openshift
      from:
        kind: DockerImage
        name: weliang/test-pod
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-openshift
    name: hello-openshift
  spec:
    replicas: 3
    selector:
      app: hello-openshift
      deploymentconfig: hello-openshift
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/container.hello-openshift.image.entrypoint: '["/hello-openshift"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: hello-openshift
          deploymentconfig: hello-openshift
      spec:
        containers:
        - image: openshift/hello-openshift
          name: hello-openshift
          ports:
          - containerPort: 8080
            protocol: TCP
            hostPort: 9736
          - containerPort: 8888
            protocol: TCP
            hostPort: 9738
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - hello-openshift
        from:
          kind: ImageStreamTag
          name: hello-openshift:latest
      type: ImageChange
  status: {}
kind: List
metadata: {}
