apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
          name: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:1.12
        user: root
        ports:
        - name: http
          containerPort: 80
          hostPort: 57119/55429/56833




