apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-mystack-nginx
  name: nginx
  namespace: mystack
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-mystack-nginx
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-mystack-nginx
    spec:
      affinity: {}
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          hostPort: 9890
          name: 80tcp98900
          protocol: TCP
        resources: {}
        stdin: true
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
