apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: hello-daemonset
spec:
  selector:
      matchLabels:
        name: blue-openshift
  template:
    metadata:
      labels:
        name: blue-openshift
    spec:
      containers:
      - image: openshift/hello-openshift
        imagePullPolicy: Always
        name: registry
        ports:
        - containerPort: 8080
          protocol: TCP
          hostPort: 2222
        resources: {}
        terminationMessagePath: /dev/termination-log
      serviceAccountName: tester
      terminationGracePeriodSeconds: 10
