apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-openshift-1
    name: hello-openshift-1
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: weliang/test-pod
      from:
        kind: DockerImage
        name: weliang/test-pod
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-openshift-1
    name: hello-openshift-1
  spec:
    replicas: 3
    selector:
      app: hello-openshift-1
      deploymentconfig: hello-openshift-1
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/container.hello-openshift-1.image.entrypoint: '["/hello-openshift-1"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: hello-openshift-1
          deploymentconfig: hello-openshift-1
      spec:
        containers:
        - image: weliang/test-pod
          command: ['sh', '-c', 'echo Hello! && sleep 3600']
          name: hello-openshift-1
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8888
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - hello-openshift-1
        from:
          kind: ImageStreamTag
          name: hello-openshift-1:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-openshift-1
    name: hello-openshift-1
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8888-tcp
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: hello-openshift-1
      deploymentconfig: hello-openshift-1
  status:
    loadBalancer: {}
kind: List
metadata: {}
