apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-openshift
    name: hello-openshift
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: weliang/test-pod
      from:
        kind: DockerImage
        name: weliang/test-pod
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-openshift
    name: hello-openshift
  spec:
    replicas: 1
    selector:
      app: hello-openshift
      deploymentconfig: hello-openshift
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/container.hello-openshift.image.entrypoint: '["/hello-openshift"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: hello-openshift
          deploymentconfig: hello-openshift
      spec:
        containers:
        - image: weliang/test-pod
          command: ['sh', '-c', 'echo Hello! && sleep 3600']
          name: hello-openshift
          ports:
          - containerPort: 7777
            protocol: TCP
            hostPort: 7777
          - containerPort: 8888
            protocol: TCP
            hostPort: 8888
          - containerPort: 9999
            protocol: TCP
            hostPort: 9999
          resources: {}
        serviceAccountName: tester
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - hello-openshift
        from:
          kind: ImageStreamTag
          name: hello-openshift:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hello-openshift
    name: hello-openshift
  spec:
    ports:
    - name: 7777-tcp
      port: 7777
      protocol: TCP
      targetPort: 7777
    - name: 8888-tcp
      port: 8888
      protocol: TCP
      targetPort: 8888
    - name: 9999-tcp
      port: 9999
      protocol: TCP
      targetPort: 9999
    selector:
      app: hello-openshift
      deploymentconfig: hello-openshift
  status:
    loadBalancer: {}
kind: List
metadata: {}
