apiVersion: v1
kind: Service
metadata:
  name: egress-dns-svc
spec:
  ports:
  - name: con1
    protocol: TCP
    port: 80
    targetPort: 80
  - name: con2
    protocol: TCP
    port: 5000
    targetPort: 8000
  - name: con3
    protocol: TCP
    port: 6000
    targetPort: 8001
  type: ClusterIP
  selector:
    name: egress-dns-pod
