apiVersion: v1
kind: Service
metadata:
  name: egress-dns-svc
spec:
  ports:
  - name: con1
    protocol: TCP
    port: 80
    targetPort: 80
  - name: con2
    protocol: TCP
    port: 443
    targetPort: 443
  - name: con3
    protocol: TCP
    port: 8080
    targetPort: 80
  - name: con4
    protocol: TCP
    port: 8443
    targetPort: 443
  type: ClusterIP
  selector:
    name: egress-dns-proxy
