# policy specifies “all red pods in namespace ‘project-a’ allow traffic from any pods in any namespace.”
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-to-red
spec:
  podSelector: 
    matchLabels:
      name: red-openshift
  ingress:
    - { }
