kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
    name: allow-from-same-namespace
spec:
    podSelector: 
    ingress:
    - from:
      - podSelector:
          matchLabels:
            type: red
