# policy specifies “all red pods in namespace ‘project-a’ allow traffic from any pods in any namespace.”
kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: allow-to-red
spec:
  podSelector: 
    matchLabels:
      name: red-openshift
  ingress:
    - { }
