kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
    name: allow-from-alice
spec:
    podSelector: 
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            user: alice
    - from:
      - podSelector: { }
