# The allow-http-and-https-ns-a policy specifies “allow ingress traffic to sockets tcp/80 and tcp/443 
# from any pod in namespace ‘project-a’ to any other pod in namespace ‘project-a’.”
kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: allow-http-and-https-ns-a
spec:
  podSelector: null
  ingress:
    - ports:
       - protocol: TCP
         port: 80
       - protocol: TCP
         port: 443
    - from:
      - podSelector: { }
