apiVersion: v1
kind: Pod
metadata:
  generateName: macvlan-vepa-pod-v6
  labels:
    name: macvlan-vepa-pod-v6
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-vepa-v6
spec:
  containers:
  - name: macvlan-vepa-pod-v6
    image: docker.io/aosqe/centos-network@sha256:48da37205f9b43424e0983d4c5e7e07f77b7ba1504bbe35e2f264c75dcb4cd15
    imagePullPolicy: IfNotPresent
