apiVersion: v1
kind: Pod
metadata:
  generateName: macvlan-vepa-pod-v6
  labels:
    name: macvlan-vepa-pod-v6
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-vepa
spec:
  containers:
  - name: macvlan-vepa-pod-v6
    image: aosqe/pod-for-ping
    imagePullPolicy: IfNotPresent
