---
kind: Pod
apiVersion: v1
metadata:
  name: blue-Pod
  labels:
    name: blue-openshift
spec:
  containers:
  - name: blue-pod-container
    image: bmeng/hello-openshift
    env:
    - name: RESPONSE
      value: Hello blue-Pod
    ports:
    - containerPort: 8080
    - containerPort: 443
