---
kind: Pod
apiVersion: v1
metadata:
  name: blue-pod-2
  labels:
    name: blue-openshift
spec:
  containers:
  - name: blue-pod-container
    image: weliang/test-pod
    command: ['sh', '-c', 'echo Hello! && sleep 3600']
    env:
    - name: RESPONSE
      value: Hello Blue Pod-2 Example
    ports:
    - containerPort: 8080
    - containerPort: 443
