apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: udp-rc
    name: udp-rc
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: udp-pods
      spec:
        containers:
        - command: 
          - "sh"
          - "-c"
          - "while true; do echo \"$(date): BROADCASTING ARP REQUEST\"; ping -c 10 yahoo.com; sleep 2; done"
          name: udp-pod
          image: library/busybox
        restartPolicy: Always
