apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: udp-rc
    name: udp-rc
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: udp-pods
      spec:
        containers:
        - command:
          - "sh"
          - "-c"
          - 'ping -q -U -c 500 -I yahoo.com;'
          name: udp-pod
          image: aosqe/pod-for-ping
        restartPolicy: Always
