#apiVersion: apps/v1beta2
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: daemonset-pod
spec:
  selector:
    matchLabels:
      name: daemonset-pod
  template:
    metadata:
      labels:
          name: daemonset-pod
    spec:
      containers:
      - name: daemonset-pod
        image: bmeng/hello-openshift
        securityContext: {}
        serviceAccount: router
        serviceAccountName: router
        ports:
        - name: http
          containerPort: 8080
          hostPort: 8888
