apiVersion: apps/v1beta2
#apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
          name: nginx
    spec:
      containers:
      - name: nginx
        image: bmeng/hello-openshift
        user: root
        ports:
        - name: http
          containerPort: 8080
          hostPort: 8888
