#oc new-project test1
#oc adm policy add-scc-to-user -z default hostnetwork -n test1
#oc create -f 

apiVersion: v1
kind: Pod
metadata:
  generateName: network-pod
spec:
  containers:
  - name: network-pod
    image: docker.io/bmeng/centos-network
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  hostNetwork: true
