---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mcast-rc
  name: mcast-rc
spec:
  replicas: 6
  template:
    metadata:
      labels:
        name: mcast-pods
    spec:
      containers:
      - image: weliang/test-pod
        name: mcast-pod
        command: ['sh', '-c', 'echo Hello! && sleep 3600']
