---
kind: Pod
apiVersion: v1
metadata:
  name: red-pod-5
  labels:
    name: red-openshift
spec:
  containers:
  - name: red-pod-container
    image: bmeng/hello-openshift
    env:
    - name: RESPONSE
      value: Hello Red Pod-5 Example
    ports:
    - containerPort: 8080
    - containerPort: 443
