apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: red-pod
    name: red-pod
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          name: acm-orion-server
      spec:
        containers:
        - image: aosqe/pod-for-ping
          name: red-pod
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: 340Mi
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: red-service
    name: red-service
  spec:
    ports:
    - name: http
      port: 27018
      protocol: TCP
      targetPort: 8080
    selector:
      name: acm-orion-server
