apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: test-pod
    name: test-pod
  spec:
    replicas: 3
    template:
      metadata:
        labels:
          name: test-pods
      spec:
        containers:
        - image: weliang/centos
          command: ['sh', '-c', 'echo Hello! && sleep 3600']
          name: test-pod
          imagePullPolicy: Always
          
