apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: multicast-pod
    name: multicast-pod
  spec:
    replicas: 3
    template:
      metadata:
        labels:
          name: multicast-pods
      spec:
        containers:
        - image: weliang/fedora-multicast
          name: multicast-pod
          imagePullPolicy: IfNotPresent
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: multicast-service
    name: multicast-service
  spec:
    ports:
    - name: http
      port: 27017
      protocol: TCP
      targetPort: 8080
    selector:
      name: multicast-pods
