---
kind: Pod
apiVersion: v1
metadata:
  name: node-exporter
  labels:
    name: node-exporter
spec:
  containers:
  - name: node-exporter
    image: bmeng/hello-openshift
    env:
    - name: RESPONSE
      value: Hello Red Pod-1 Example
    ports:
    - containerPort: 8080
    - containerPort: 443
