apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: weliang/centos
    command: ['sh', '-c', 'echo Hello! && sleep 3600']
