apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 8800
    targetPort: 80
  selector:
    app: my-nginx

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: my-nginx
        image: nginx:1.8.1
        ports:
        - containerPort: 8080
          protocol: TCP
