apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: test-pod
    name: test-pod
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: test-pods
      spec:
        containers:
        - image: weliang/test-pod
          name: test-pod
          imagePullPolicy: IfNotPresent
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: test-service
    name: test-service
  spec:
    ports:
    - name: http
      port: 27017
      protocol: TCP
      targetPort: 8080
    selector:
      name: test-pods
