---
kind: List
apiVersion: v1
metadata:
  name: hello-service-complete-example
items:
- kind: Pod
  apiVersion: v1
  metadata:
    name: hello-pod-1
    labels:
      name: hello-openshift
  spec:
    containers:
    - name: hello-pod-container-1
      image: weliang/test-pod
      ports:
      - containerPort: 8080
      - containerPort: 443
- kind: Pod
  apiVersion: v1
  metadata:
    name: hello-pod-2
    labels:
      name: hello-openshift
  spec:
    containers:
    - name: hello-pod-container-2
      image: weliang/test-pod
      ports:
      - containerPort: 8080
      - containerPort: 443
 - kind: Pod
  apiVersion: v1
  metadata:
    name: hello-pod-3
    labels:
      name: hello-openshift
  spec:
    containers:
    - name: hello-pod-container-3
      image: weliang/test-pod
      ports:
      - containerPort: 8080
      - containerPort: 443
