## Headless svc is to mark clusterIP to be None and nslookup svc will get endpoints IP
---
kind: Service
apiVersion: v1
metadata:
  name: blue-service
spec:
  selector:
    name: blue-openshift
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  clusterIP: None
