apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridgevlan100
spec:
  config: '{
          "name": "bridgevlan",
          "type": "bridge",
          "ipMasq": true,
          "bridge": "mybridge",
          "ipam": {
                    "type": "host-local",
                    "subnet": "22.2.2.0/24",
                    "rangeStart": "22.2.2.100",
                    "rangeEnd": "22.2.2.120"
          },
          "isDefaultGateway": true,
          "forceAddress": false,
          "ipMasq": true,
          "hairpinMode": true,
          "vlan": 100
  }'
