apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridgeL2
spec:
  config: '{
          "name": "bridgeL2",
          "type": "bridge",
          "bridge": "bridgeL2",
          "ipam": { }
  }'
