apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  additionalNetworks: 
  - name: test-network-1
    type: Raw
    rawCNIConfig: '{
      "cniVersion": "0.3.1",
      "type": "bridge",
      "master": "ens5",
      "ipam": {
                    "type": "static",
                    "addresses": [
                        {
                          "address": "22.2.2.2/24",
                          "gateway": "22.2.2.254"
                        }
                    ]
              }
    }'
