apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipam-static1 
spec:
  config: '{
          "name": "ipam-static1",
          "type": "ipvlan",
          "master": "ens5",
          "ipam": {
                    "type": "static",
                    "addresses": [
                        {
                          "address": "22.2.2.2/24",
                          "gateway": "22.2.2.254"
                        }
                    ]
          }
  }'
