apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-ipam-static 
spec:
  config: '{
          "name": "macvlan-ipam-static",
          "type": "macvlan",
          "mode": "bridge",
          "master": "ens5",
          "ipam": {
                    "type": "static",
                    "addresses": [
                        {
                          "address": "22.2.2.3/24",
                          "gateway": "22.2.2.254"
                        }
                    ]
          }
  }'
