apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-ipam-host-local
spec:
  config: '{
          "name": "macvlan-ipam-host-local",
          "type": "macvlan",
          "mode": "macvlan-mode",
          "master": "ens3",
          "ipam": {
            "type": "host-local",
            "subnet": "fd00::66:6:6:0/112",
            "rangeStart": "fd00::66:6:6:100",
            "rangeEnd": "fd00::66:6:6:200"
      }
  }'
