apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-bridge
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "20.1.1.0/24",
        "rangeStart": "20.1.1.100",
        "rangeEnd": "20.1.1.200",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "20.1.1.1"
      }
    }'
