apiVersion: v1
kind: Pod
metadata:
  name: multicast-macvlan-host-local-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: multicast-macvlan-host-local
spec:
  containers:
  - name: multicast-macvlan-host-local-pod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: weliang/test-pod
