apiVersion: v1
kind: Pod
metadata:
  name: pod-ipvlan-local-host
  annotations:
    k8s.v1.cni.cncf.io/networks: myipvlan-1
spec:
  containers:
  - name: pod-ipvlan-local-host
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
