apiVersion: v1
kind: Pod
metadata:
  name: pod-bridgelayer2
  annotations:
    k8s.v1.cni.cncf.io/networks: bridgelayer2
spec:
  containers:
  - name: pod-bridgelayer2
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
