apiVersion: v1
kind: Pod
metadata:
  name: pod-novlan
  annotations:
    k8s.v1.cni.cncf.io/networks: bridge3
spec:
  containers:
  - name: pod-novlan
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
