apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  annotations:
    k8s.v1.cni.cncf.io/networks: net-attach-def
spec:
  containers:
  - name: pod-name
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
