apiVersion: v1
kind: Pod
metadata:
  name: pod2-vlan200
  annotations:
    k8s.v1.cni.cncf.io/networks: bridgevlan
spec:
  containers:
  - name: pod2-vlan200
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
