apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: runtimeconfig-def-ip
spec: 
  config: '{
            "cniVersion": "0.3.1",
            "name": "runtimeconfig-def-ip",
            "plugins": [
                {
                    "type": "macvlan",
                    "capabilities": { "ips": true },
                    "master": "ens5",
                    "mode": "bridge",
                    "ipam": {
                        "type": "static"
                    }
                } ]
   }'
