#192.168.10.0/29  HOST RANGE:192.168.10.1 – 192.168.10.6
#192.168.10.0/30  HOST RANGE: 192.168.10.1 – 192.168.10.2
#192.168.10.6/32


apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata: 
  name: macvlan-bridge-whereabouts
spec: 
  config: '{
      "cniVersion": "0.3.0",
      "name": "whereabouts",
      "type": "macvlan",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts", 
        "range": "192.168.10.0/29", 
        "exclude": [ 
          "192.168.10.0/30",
          "192.169.10.6/32"
        ],
      }
}'
