---
kind: List
apiVersion: v1
metadata:
  name: hello-service-complete-example
items:
- kind: Route
  apiVersion: v1
  metadata:
    name: edge-route
    labels:
      name: edge-route
  spec:
    host: edgeroute.example.com
    to:
      kind: Service
      name: edgeroute-service
    tls:
      termination: edge
      certificate: |
        -----BEGIN CERTIFICATE-----
        MIICszCCAZsCAQAwbjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRYwFAYDVQQHDA1Nb3VudGFpbiBWaWV3MQwwCgYDVQQKDANPUzMxDDAKBgNVBAsMA0VuZzEeMBwGA1UEAwwVZWRnZXJvdXRlLmV4YW1wbGUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5Qyvc3iddzWzSKHTQdWWaoI14RVrdd5Q5qEqkTuJDh0uUbZ3RK8xgc1MF+aFquzvQivOUhDQTckehj6CVS/1i0a8g6XE58tdXcM367PjUkrvXcGzxbEOHzB2q7DFfQr8FXvOrmGJioOk5FbPePXMSqQU9iFLftgH3Uh9Bu8TrbvPQOPX6UciEVDdZEx+XIPp3RMHdY+CmxpErUeVKnAQwNqtN/ZF4FSEUszrbm6nNAkL+K48D7rHALyLZHStu9o6OLjtLU9t01CIxWbgQvLssdoi4yhKfJV6tmKgNKQ6Ze6iZ+2pcsFg1xbsDPEqR/UU1NMYwWlE8+eq7Vup+hegVQIDAQABoAAwDQYJKoZIhvcNAQELBQADggEBAE8IFIsJYYnP81P0hYItfuN6td1Cli2yQrpCpyimamVVAIH3t5YnqotvsoRdUbgtP+dhJsVK0JxC8j9EEUbcoNVLcYNLAucbWtJqEqkSuNxvN06FqasmxhYJyw96pLXEwP3PkfQrMspuqXUgpKP3xRAvdRicYUl9uyg7msM+jCRtivNXVFYpfb/pLuw9Pd1FaVzWaYMHMDkZKG/ZACFPGHD8LWz1wID7bQf5cfDq+b7fzgnNfI6LlYbzA7SljjjETuO5KuoYT2Xu1E0KzSim8KChFr/J1F8BRJmDhuu8G5CWn+/BGbzUVt1tLyoFZOhbm6IkxYFRV00Ws+t1TipLjpA=
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpgIBAAKCAQEA5Qyvc3iddzWzSKHTQdWWaoI14RVrdd5Q5qEqkTuJDh0uUbZ3RK8xgc1MF+aFquzvQivOUhDQTckehj6CVS/1i0a8g6XE58tdXcM367PjUkrvXcGzxbEOHzB2q7DFfQr8FXvOrmGJioOk5FbPePXMSqQU9iFLftgH3Uh9Bu8TrbvPQOPX6UciEVDdZEx+XIPp3RMHdY+CmxpErUeVKnAQwNqtN/ZF4FSEUszrbm6nNAkL+K48D7rHALyLZHStu9o6OLjtLU9t01CIxWbgQvLssdoi4yhKfJV6tmKgNKQ6Ze6iZ+2pcsFg1xbsDPEqR/UU1NMYwWlE8+eq7Vup+hegVQIDAQABAoIBAQCf57hBXA5KoDHW3ir3Rh6potfsmKCZ/Cfsqs1l8PNg6BxjLYicadadMO8TrHra9miegKicgGJ8O5FU1ST2RfIdVrfbDIqn7ED1aYmLwt1LoUb05HsV4+LhAVuHx3RINLgCY5nKAgwcqIUgaD6VyrvhzCVaI6pqFnV/FdE7WwMZALeHLQnpJU1CJCMsjA8rTpTy4CgTan+xovrUJnNO8ElWwRQQHJVu9cjqRXegCxd1uQ0FgXfWAvaYS4unqQBuCC+SENbzyGVlLg9hEhZORw6EkgLhhRK8jk4o0PiMR3jQsYWzcEuFGvtHoD41T2WDR7F1oL8RHo5Rl1mZzSCFas4hAoGBAPpmOl2Oidqo2MgtYRIW9zEq9rds7PtKzjFwdXMeNWpTxVrIYOLrh7jyQ3CIIdQhl5hCGBP+/V1zCMPxeWAo4FSPKX/e07O9cci6XahnPteRCfrwoNqqyBA4dX2iDWXIYe8VPDyjpRBBhfOIjYxlFoB4pDUEPU2ZuzegMN7n7J45AoGBAOosNbS2RWSBrdoAa6PTMfQl/8Kh9tZc3a8CSYiHRWtfnPgN9wmf9qGDVmEOzkd886NtL2c41i9LUb08lLJVWiNJgnwrcZ7wiTZXzlTg+N8vtGmGxpg8dvLKsrrLwBEsCWIRoDP7NxpNHD5MU6pnlRIIkQEUzR5VZxlOcFW/GVL9AoGBAOf40NVfeaKSjdJVB/qkP/jS3qFrTdg3ovH2RziQodeRJ+JEhE10+dWCyqtz0jMds70gbgIIVly+dz5fdJx7AegUgNOvcNyxArp8vMuIapV2DpLlXX92e8VbKK1s9ZB3pRLCz3019XMr4JaOyONpuwDlwupCtTAw3VpZEy1OGs0xAoGBAMj/AWoHOTC3jj2cNsf7MtlY9FpfIruEIlNhJzSkxxUOkHDpq6z7PHoNfUr5plz+BzGzOgjjZBRcFeDT6t3XHPNE2VczAudllqCqZVO9dmA7ViNtp3BsFbz39skWsdkLb1JZxqRXcEiG/0MJyJZvKii8aZn//L+YllHGXe17hYURAoGBAI3mXlxJzeIFYNBep5Ok8knNkTIQYQHdrWxTV4UbHEtYtCA+qfmuEfx/1hMrxh4rb7DiC/MzBuQxaPWwF3gsT4TQSsZQSg1qd1kiogCAW+mHKibm4b70Kg+kaT5ev/9GVpuVXMXmtSuFt/I81tZ5DNW4re9ai0wqKNMECjR6HmFo
        -----END RSA PRIVATE KEY-----
- kind: Service
  apiVersion: v1
  metadata:
    name: edgeroute-service
  spec:
    selector:
      name: edgeroute-openshift
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
- kind: Pod
  apiVersion: v1
  metadata:
    name: edgeroute-pod
    labels:
      name: edgeroute-openshift
  spec:
    containers:
    - name: edgeroute-pod-container
      image: openshift/hello-openshift
      env:
      - name: RESPONSE
        value: Hello EdgeRoute Example
      ports:
      - containerPort: 8080
      - containerPort: 443
