---
kind: List
apiVersion: v1
metadata:
  name: hello-service-complete-example
items:
- kind: Route
  apiVersion: v1
  metadata:
    name: edgeroute-route
    labels:
      name: edgeroute-route
  spec:
    host: edgeroute.example.com
    to:
      kind: Service
      name: edgeroute-service
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
      certificate: |
        -----BEGIN CERTIFICATE-----
        MIIDWDCCAkACCQDvIzombGf0YDANBgkqhkiG9w0BAQsFADBuMQswCQYDVQQGEwJVUzELMAkGA1UECAwCQ0ExFjAUBgNVBAcMDU1vdW50YWluIFZpZXcxDDAKBgNVBAoMA09TMzEMMAoGA1UECwwDRW5nMR4wHAYDVQQDDBVlZGdlcm91dGUuZXhhbXBsZS5jb20wHhcNMTgwOTE5MjAxNzE4WhcNMjgwOTI2MjAxNzE4WjBuMQswCQYDVQQGEwJVUzELMAkGA1UECAwCQ0ExFjAUBgNVBAcMDU1vdW50YWluIFZpZXcxDDAKBgNVBAoMA09TMzEMMAoGA1UECwwDRW5nMR4wHAYDVQQDDBVlZGdlcm91dGUuZXhhbXBsZS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvN9qItPQIMl/Il0BXvLS26m0xYk+O33GToT9ZWAWje50wYpzGhweudzmGpQ+c6Hs7kMAZ8wimaVjPLfe7bNOFBUezxxgtRws5WrBMjiwOAKjUP6zAVW4y5Y7Z7i9p6lT94g16WYOqnWaC11IuSEfMHxVebM6kqgV+/f6Jp8RMnWW6b4xPkYTpotsmCUh/SJ2X2rhilRQPvMZUDOrWESjfERjktOppBxExlTuqUL1TxP11rqixCJz7pUwYKxeuo1MqNdgXFHDPjTd88XhaPGyD1qT/Bhip7NwUcM/znWaD05Kt/KhTTES20l7PMrWNmp9znB/L0SFu13xTQgKQ4gPpAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAFxKqO2UJE3YWrab65wpsJVttClbXGs5oN5BmGBvjxFMB+knNzC515FTiJJ/CqMn/cv69+jSxWvvckcTfN4WE4AHbcKhFesDdVEKOPTJHbT/PVhEItDT3rAqROTRgfbUudd2avmD7ZTwABQeb6SccZ4tAulbiJ4FdGj7FKuo3vF3xXNEs5gOARco+phtDxG51douQYB4//vJIQERcMTfgW6B7SLhibwIdQK93cg5uzt2SjgFPpyLtjosvvp10vYWq7PQny5a4PVNJqa/d20DoBjESMHTcc7IIsWuZTlL5xDrEnZBL9KsTiXo+R4NfaF2BGt4BkOnJmsu4YI8SSnH8W0=
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEArzfaiLT0CDJfyJdAV7y0tuptMWJPjt9xk6E/WVgFo3udMGKcxocHrnc5hqUPnOh7O5DAGfMIpmlYzy33u2zThQVHs8cYLUcLOVqwTI4sDgCo1D+swFVuMuWO2e4vaepU/eINelmDqp1mgtdSLkhHzB8VXmzOpKoFfv3+iafETJ1lum+MT5GE6aLbJglIf0idl9q4YpUUD7zGVAzq1hEo3xEY5LTqaQcRMZU7qlC9U8T9da6osQic+6VMGCsXrqNTKjXYFxRwz403fPF4Wjxsg9ak/wYYqezcFHDP851mg9OSrfyoU0xEttJezzK1jZqfc5wfy9Ehbtd8U0ICkOID6QIDAQABAoIBAFhXzexNaBjV5StK71sNPwRWsBVNHxXHHQm1LC6MzdL+mWNy5N7H6ByT6kIz6OpQ4QlIU0MCIWNeDDPxVk1+citIXT2MbWkuv778NZVzvUyWEolpTV1v9W7eBSdmCyvYxV94YRlGFreoQq5HiBzjvqdxKKICNDIbs0ezImofVz7U62WWKqXzsgJSC7yvjzfNiupUILaYJiFxZe/vuzGmeLYW4+nnPE8NdYt0EuPg3gkaxz0DiOiU/PaC7d5BE4R34RsmR1ikOhsafA93d8MBK8HQOodTJ2aKUq80E/WqpNL9o0VATMZGJkYFaG9FOWwtEjeAG6pajHceWs5gZyrs5gECgYEA28B5RiMMNq5u8Lev37ldreunr6QdzARGUTvMRz+l7/L9hUofC1/cTWLi58YGmrhRnq8vtIBg8o0DFnyOD1w478Dx33opotLiL/gYB5PTom55R25N8NkJJ5l3324NlWa6UrTxOVMvo0uA/fx1eHhzJ83GPnp01OKYLeK59UTAOqkCgYEAzB7X6PCXX34WHFmjUDADeYROp1JT4qQjYs7e9TBXMzc28Z0GVP8ouvvUIJabg/BlPnBiaaoJGAYu1Ltg5fkfb0usxnTVxa3bK8MUrwmyXH7WygKgEhwimOkms+Bdhi7QREATrzj8lykEdSuq3SxohRnKHEXGwjArfSqttU6Eh0ECgYB7gSxnl9EIdnbRgVsuMP8OfXBMDb/VZt2iUCpaLNJ1DisgG21hNioZsCb4vln94PO2bJ0yJCjYiRogLDanOVyimt0VjZIS+dS3wwa2U4XRN6ef1sWlREWZ5O3zO+YUfpzfWORuJGuUqh3AIYBgCcomp8bwXGCHOSbwOwnqaA5lqQKBgEJQ0vzPDZ7sq+pSBQkMUFSuc49Q5AgCI6z6YN1v8ySkj6k3xtLegzEcl/Jue+AFvh7nDFIf+AxiFdzvc6/DnD7gayWe18T9kvNI0fN8RwJeAxJmf/LiSSs8tGJERp5Nn0RNPRf0f7vsi5I1ubFZuCtmEY/V65kzZS2pK/53n/8BAoGBAKvrC9OfreaOfFa/DsDTfcSA2ZVoZs3TR/vaGn9LZHNqxgrI4IvMgA3vtqoxlsCfNtqJRldwBMykAD7k53591+TZPvaka18oqkmM+48iSiMgZbTc7uesUbztmBiuTOdlErJ2tKH612geHCaTavKyA1w4tful36VCzIP5/D4KcClc
        -----END RSA PRIVATE KEY-----
- kind: Service
  apiVersion: v1
  metadata:
    name: edgeroute-service
  spec:
    selector:
      name: edgeroute-openshift
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
- kind: Pod
  apiVersion: v1
  metadata:
    name: edgeroute-pod
    labels:
      name: edgeroute-openshift
  spec:
    containers:
    - name: edgeroute-pod-container
      image: openshift/hello-openshift
      env:
      - name: RESPONSE
        value: Hello EdgeRoute
      ports:
      - containerPort: 8080
      - containerPort: 443
