apiVersion: v1
kind: Pod
metadata:
  name: sctpclient
  labels:
    app: sctpclient
spec:
  containers:
    - name: sctpclient
      image: fedora
      command: ["/bin/sh", "-c"]
      args:
        ["dnf install -y iperf && sleep inf"]
      
