apiVersion: v1
kind: Pod
metadata:
  name: sctpserver
  labels:
    app: sctpserver
spec:
  containers:
    - name: sctpserver
      image: fedora:31
      command: ["/bin/sh", "-c"]
      args:
        ["dnf install -y nc && nc -l 30102 --sctp"]
      ports:
        - containerPort: 30102
          name: sctpserver
          protocol: SCTP
