apiVersion: v1
kind: Service
metadata:
  name: fedeservice
  labels:
    app: sctpserver
spec:
  selector:
    app: sctpserver
  ports:
    - name: sctpserver
      protocol: SCTP
      port: 30101
      targetPort: 'sctpserver'
  type: NodePort
