apiVersion: v1
kind: Pod
metadata:
  generateName: sctpclient-
  labels:
    app: sctpclient
spec:
  containers:
    - name: sctpclient
      image: fedora:31 
      command: ["/bin/sh", "-c"]
      args:
        ["dnf install -y nc && sleep inf"]
