apiVersion: v1
kind: Pod
metadata:
  name: sctpserver
  labels:
    app: sctpserver
spec:
  containers:
    - name: sctpserver
      image: fedora
      command: ["/bin/sh", "-c"]
      args:
        ["dnf install -y iperf && sleep inf"]
      ports:
        - containerPort: 30102
          name: sctpserver
          protocol: SCTP
