apiVersion: v1
kind: Pod
metadata:
  name: sctpserver
  labels:
    app: sctpserver
spec:
  containers:
    - name: sctpserver
      image: registry.access.redhat.com/ubi8/ubi
      command: ["/bin/sh", "-c"]
      args:
        ["dnf install -y nc && /usr/bin/ncat -l 30102 --sctp"]
      ports:
        - containerPort: 30102
          name: sctpserver
          protocol: SCTP
